### ISSUE TITLE
error C2679 build with windows vs2019 (LLVM9.0.1+ TVM0.6.1)

### ISSUE THREAD

**Issue by SpaceView** [apache/incubator-tvm#6071]
Problem (1):
I was trying to build tvm under windows with VS2019,  and succeeded with the following versions:
LLVM9.0.1+TVM0.6.0
LLVM9.0.1+(the most updated, i.e., git clone --recursive https://github.com/apache/incubator-tvm.git)
but,
when I'm trying with TVM0.6.1, I got the following 2 erros (C2679), and I tried with packages from https://tvm.apache.org/download, it gave me the same error as below, 
I check the codes and cannot figure out any clue, could anybody help?

`
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\list(1285,1): error C2679: 二进制“=”: 没有找到接受“const std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>”类型的右操作数的运算符(或没有可接受的转换)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\utility(233,11): message : 可能是“std::pair<_Kty,_Ty> &std::pair<_Kty,_Ty>::operator =(volatile const std::pair<_Kty,_Ty> &)”
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\utility(275,11): message : 或    “std::pair<_Kty,_Ty> &std::pair<_Kty,_Ty>::operator =<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,0>(std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>> &&) noexcept(<expr>)”
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\utility(251,11): message : 或    “std::pair<_Kty,_Ty> &std::pair<_Kty,_Ty>::operator =<std::pair<_Kty,_Ty>,0>(std::pair<_Kty,_Ty> &&) noexcept(<expr>)”
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\list(1285,1): message : 尝试匹配参数列表“(std::pair<_Kty,_Ty>, const std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>)”时
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(876): message : 查看对正在编译的函数 模板 实例化“void std::list<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>,std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>::_Assign_cast<std::pair<_Kty,_Ty>&,std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>>(_UIter,const _UIter)”的引用
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
2>            _UIter=std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(875): message : 查看对正在编译的函数 模板 实例化“void std::list<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>,std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>::_Assign_cast<std::pair<_Kty,_Ty>&,std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>>(_UIter,const _UIter)”的引用
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
2>            _UIter=std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(871): message : 在编译 类 模板 成员函数“void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Copy_assign(const std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>> &,std::false_type)”时
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
2>            _Hasher=std::hash<std::string>,
2>            _Keyeq=std::equal_to<std::string>,
2>            _Alloc=std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(908): message : 查看对正在编译的函数 模板 实例化“void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Copy_assign(const std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>> &,std::false_type)”的引用
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
2>            _Hasher=std::hash<std::string>,
2>            _Keyeq=std::equal_to<std::string>,
2>            _Alloc=std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>
2>        ]
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\unordered_map(69): message : 查看对正在编译的 类 模板 实例化“std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>”的引用
2>        with
2>        [
2>            _Kty=std::string,
2>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
2>            _Hasher=std::hash<std::string>,
2>            _Keyeq=std::equal_to<std::string>,
2>            _Alloc=std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>
2>        ]
2>O:\devTVM\tvm061rc1\include\tvm\runtime\module.h(210): message : 查看对正在编译的 类 模板 实例化“std::unordered_map<std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>”的引用
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\numeric(35,26): warning C4244: “=”: 从“_Ty”转换到“_Ty”，可能丢失数据
1>        with
1>        [
1>            _Ty=int64_t
1>        ]
1>        and
1>        [
1>            _Ty=int
1>        ]
1>O:\devTVM\tvm061rc1\src\runtime\graph\graph_runtime.cc(378): message : 查看对正在编译的函数 模板 实例化“_Ty std::accumulate<int64_t*,int,std::multiplies<int64_t>>(const _InIt,const _InIt,_Ty,_Fn)”的引用
1>        with
1>        [
1>            _Ty=int,
1>            _InIt=int64_t *,
1>            _Fn=std::multiplies<int64_t>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\list(1285,1): error C2679: 二进制“=”: 没有找到接受“const std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>”类型的右操作数的运算符(或没有可接受的转换)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\utility(233,11): message : 可能是“std::pair<_Kty,_Ty> &std::pair<_Kty,_Ty>::operator =(volatile const std::pair<_Kty,_Ty> &)”
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\utility(275,11): message : 或    “std::pair<_Kty,_Ty> &std::pair<_Kty,_Ty>::operator =<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,0>(std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>> &&) noexcept(<expr>)”
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\utility(251,11): message : 或    “std::pair<_Kty,_Ty> &std::pair<_Kty,_Ty>::operator =<std::pair<_Kty,_Ty>,0>(std::pair<_Kty,_Ty> &&) noexcept(<expr>)”
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\list(1285,1): message : 尝试匹配参数列表“(std::pair<_Kty,_Ty>, const std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>)”时
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(876): message : 查看对正在编译的函数 模板 实例化“void std::list<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>,std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>::_Assign_cast<std::pair<_Kty,_Ty>&,std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>>(_UIter,const _UIter)”的引用
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
1>            _UIter=std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(875): message : 查看对正在编译的函数 模板 实例化“void std::list<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>,std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>::_Assign_cast<std::pair<_Kty,_Ty>&,std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>>(_UIter,const _UIter)”的引用
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
1>            _UIter=std::_List_unchecked_const_iterator<std::_List_val<std::_List_simple_types<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>,std::_Iterator_base0>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(871): message : 在编译 类 模板 成员函数“void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Copy_assign(const std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>> &,std::false_type)”时
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
1>            _Hasher=std::hash<std::string>,
1>            _Keyeq=std::equal_to<std::string>,
1>            _Alloc=std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\xhash(908): message : 查看对正在编译的函数 模板 实例化“void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::_Copy_assign(const std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>> &,std::false_type)”的引用
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
1>            _Hasher=std::hash<std::string>,
1>            _Keyeq=std::equal_to<std::string>,
1>            _Alloc=std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>
1>        ]
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\unordered_map(69): message : 查看对正在编译的 类 模板 实例化“std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>”的引用
1>        with
1>        [
1>            _Kty=std::string,
1>            _Ty=std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,
1>            _Hasher=std::hash<std::string>,
1>            _Keyeq=std::equal_to<std::string>,
1>            _Alloc=std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>
1>        ]
1>O:\devTVM\tvm061rc1\include\tvm\runtime\module.h(210): message : 查看对正在编译的 类 模板 实例化“std::unordered_map<std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<const std::string,std::unique_ptr<tvm::runtime::PackedFunc,std::default_delete<tvm::runtime::PackedFunc>>>>>”的引用
`

Problem(2):
I installed the above built versions (python setup.py install --user)
LLVM9.0.1+(the most updated, i.e., git clone --recursive https://github.com/apache/incubator-tvm.git)
but it seems to be not OK within python, as below,

Python 3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "O:\devTVM\incubator-tvm\python\tvm\__init__.py", line 25, in <module>
    from ._ffi.base import TVMError, __version__
  File "O:\devTVM\incubator-tvm\python\tvm\_ffi\__init__.py", line 28, in <module>
    from .base import register_error
  File "O:\devTVM\incubator-tvm\python\tvm\_ffi\base.py", line 62, in <module>
    _LIB, _LIB_NAME = _load_lib()
  File "O:\devTVM\incubator-tvm\python\tvm\_ffi\base.py", line 50, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "d:\Anaconda3\envs\mx36gpu\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。

**Comment by tqchen** [comment]
Could you please open a thread in the discussion forum https://discuss.tvm.ai? We generally use the forum to such discussions. Thanks.
